### ISSUE TITLE
[ERROR] [Engine$] No engine found. Your build might have failed. Aborting. - using PredictionIO-0.11.0-incubating scala.version=2.11.6 spark.version=2.1.0 elasticsearch.version=2.3.3

### ISSUE THREAD

**Issue by washingon** [peoplehum/template-Labelling-Topics-with-wikipedia#3]
When I try to build the engine, I get error [INFO] [Engine$] Looking for an engine...
[ERROR] [Engine$] No engine found. Your build might have failed. Aborting.

I built pio with scala 2.11.6.

Why is the engine building for scala-2.10 instead of scala-2.11?

[INFO] [Engine$] Compilation finished successfully.
[INFO] [Engine$] Looking for an engine...
[ERROR] [Engine$] No engine found. Your build might have failed. Aborting.

**Comment by washingon** [comment]
edit build.sbt to build successfully with scala 2.11.6 and PredictionIO-0.11.0-incubating.

build.sbt:
```
assemblySettings

name := "WikiClassifier"

organization := "org.apache.predictionio"

scalaVersion := "2.11.6"

libraryDependencies ++= Seq(
 "org.apache.predictionio" %% "apache-predictionio-core" % "0.11.0-incubating" % "provided",
  "org.apache.spark"        %% "spark-core"               % "1.5.1" % "provided",
 "org.apache.spark"        %% "spark-mllib"              % "1.5.1" % "provided")

```

**Comment by anandaverma** [comment]
Hi @washingon @bansarishah is looking at it and will update you shortly. It looks like software version issue mostly.

**Comment by ebuildy** [comment]
@anandaverma you don't have to update your code, this is a very common "mistake" with Scala. 

All predictionIO "plugins" have different scala version, so the user must set scalaVersion to match the one used to build predictionIO.

**Comment by bansarishah** [comment]
Hi @ebuildy, Thank You. 
yes, it is a mistake with scala version.
@washingon to build this model, you will require matching scala version 2.10.6.
Building with different version may have some issue.
